### ISSUE TITLE
[Bug] gateway auth 中缺少 `/douyin/user/` 接口

### ISSUE THREAD

**Issue by Maple-pro** [GuGoOrg/GuGoTik#104]
https://apifox.com/apidoc/shared-09d88f32-0b6c-4157-9d07-a36d32d7a75c/api-50707524

**Comment by liaosunny123** [comment]
completed via https://github.com/GuGoOrg/GuGoTik/commit/1510ac01bfa193492ed10f50e7a1ebe7f20a59af
