### ISSUE TITLE
[Bug] 依赖 Service 初始化问题

### ISSUE THREAD

**Issue by Maple-pro** [GuGoOrg/GuGoTik#114]
目前的依赖 Service 发现是在 `init` 里面完成的，但这出现了两个问题：
- 无法解决循环依赖问题
- 没有服务重连

解决方案：
在 Sevice Server 创建时添加 gRPC 中间件，在每个 handler 执行前初始化所有依赖的 Sevice Client
- 如果已连接，不用管；
- 如果未连接，重连；
- 重连失败不执行 handler

**Comment by liaosunny123** [comment]
completed via https://github.com/GuGoOrg/GuGoTik/commit/c0b8ea9385eec6a0a88a92032eaf74d3b6a431f5
