### ISSUE TITLE
Bug：重复关注

### ISSUE THREAD

**Issue by liaosunny123** [GuGoOrg/GuGoTik#128]
数据库发现存在重复关注的现象
![image](https://github.com/GuGoOrg/GuGoTik/assets/30096937/c23ec290-8982-445e-bffe-e4c831d9c026)

**Comment by liaosunny123** [comment]
![image](https://github.com/GuGoOrg/GuGoTik/assets/30096937/7448c224-06af-41cc-8563-226fecc3f677)
Follow Count因此被错误统计了

**Comment by ExerciseBook** [comment]
日志表才有 actor 列吧，实体表为啥会有 actor

因为要动作/行为 才有 actor。

不过问题不大，又不是不能用。

**Comment by liaosunny123** [comment]
> 动作/事件之类的日志表才有 actor 列吧，实体表为啥会有 actor
> 
> 因为要动作/行为 才有 actor。
> 
> 不过问题不大，又不是不能用。

这个是relation那边的逻辑，他似乎是 actor：关注者，user_Id：被关注者，一行表示一个关注操作

**Comment by ExerciseBook** [comment]
奥，那这样的话这个表记录重复了就无所谓了。

**Comment by liaosunny123** [comment]
> 奥，那这样的话这个表记录重复了就无所谓了。最后统计结果没错就行。
> 
> 如果出现重复计算了，也不是什么太大的问题。放到后续搞个异步来同步回填正确的关注数应该合理。

不过问题在于统计结果也错了，笑哭

**Comment by amazing-compass** [comment]
重复关注 ok
redis和数据库正常
