### ISSUE TITLE
fix: getUser 缺少字段

### ISSUE THREAD

**Issue by Maple-pro** [GuGoOrg/GuGoTik#129]
前端 API 要求的 user 字段：

<img width="224" alt="image" src="https://github.com/GuGoOrg/GuGoTik/assets/52351480/279a143f-165a-474b-bfe4-7721ecd827fe">

目前已有的 user 字段：

<img width="511" alt="image" src="https://github.com/GuGoOrg/GuGoTik/assets/52351480/8f3c71af-0d38-41af-b790-13d4f662103e">

**Comment by liaosunny123** [comment]
Do not have this problem
