### ISSUE TITLE
Bug：无法获取聊天记录

### ISSUE THREAD

**Issue by liaosunny123** [GuGoOrg/GuGoTik#138]
![image](https://github.com/GuGoOrg/GuGoTik/assets/30096937/49d89659-974d-4a74-9ccb-0bf034d65a7d)
链路：
![image](https://github.com/GuGoOrg/GuGoTik/assets/30096937/239fc217-83b8-45fe-849c-fe399422ddd9)
![image](https://github.com/GuGoOrg/GuGoTik/assets/30096937/4b7a2d13-37a2-4b84-8643-b63ee85320a0)

**Comment by Maple-pro** [comment]
Done by #146
