### ISSUE TITLE
Bug：点赞数据不符合预期

### ISSUE THREAD

**Issue by liaosunny123** [GuGoOrg/GuGoTik#142]
对不存在的用户(UserId=-1)做点赞列表获取，能够获取到数据
![image](https://github.com/GuGoOrg/GuGoTik/assets/30096937/935d3dc0-1cb4-4b9d-a58d-e6529d943cf8)

**Comment by XFFFCCCC** [comment]
这个因为点赞时候，没有对用户id进行判断
