### ISSUE TITLE
Bug：点赞视频列表获取出错

### ISSUE THREAD

**Issue by liaosunny123** [GuGoOrg/GuGoTik#143]
点赞获取用户信息，用户信息获取点赞的时候，点赞服务出错
![image](https://github.com/GuGoOrg/GuGoTik/assets/30096937/9c1cc421-2482-476f-bb69-053377c0e028)
![image](https://github.com/GuGoOrg/GuGoTik/assets/30096937/8ac266d1-15ab-4c93-877c-818a3d377c46)
![image](https://github.com/GuGoOrg/GuGoTik/assets/30096937/27e1749d-9f04-4c0d-b162-a9ce7f083894)
![image](https://github.com/GuGoOrg/GuGoTik/assets/30096937/51a98098-843a-4825-8d71-2d3558164072)

**Comment by XFFFCCCC** [comment]
这个还能找到日志吗
