### ISSUE TITLE
测试前端设计

### ISSUE THREAD

**Issue by 1234238** [GuGoOrg/GuGoTik#240]
您好，请问此项目的前端设计是如何实现的呢，我目前看测试是通过postman和测试代码进行测试，如何能看到可视化的效果呢？或者说我需要学习哪方面的东西呢？

**Comment by liaosunny123** [comment]
你好，这个项目是基于字节的青训营-后端方向的选题做的。因此给我们提供了测试 App，我们提供后端对接即可测试。

如果需要前端，可以自行学习如何制作 App，或者是网页

**Comment by 1234238** [comment]
> 你好，这个项目是基于字节的青训营-后端方向的选题做的。因此给我们提供了测试 App，我们提供后端对接即可测试。
> 
> 如果需要前端，可以自行学习如何制作 App，或者是网页

非常感谢您的回复！

**Comment by 1234238** [comment]
> 你好，这个项目是基于字节的青训营-后端方向的选题做的。因此给我们提供了测试 App，我们提供后端对接即可测试。
> 
> 如果需要前端，可以自行学习如何制作 App，或者是网页

  Hello，非常感谢您之前的回复。
  近期我开始学习这个项目，我在阿里云租了一个2核(vCPU) 4 GiB的服务器来部署，不过似乎性能不太够？请问您是否对服务器要求有一个大概评估呢？
  祝好

**Comment by 1234238** [comment]
尊敬的作者，你好
  前段时间我找到这个项目，并开始学习，这个项目非常的棒，里面涉及到了比较多的业务逻辑，我认为是非常棒的一个项目。但是在阅读文档后我还有一些问题希望向您请教。
  在启动web文件下的main.go后, 我的程序产生了`2024/10/06 11:36:47 ERROR: [Consul resolver] Couldn't update client connection. error={bad resolver state}`的报错。我随后查看源码的过程中依旧不太理解产生的原因，在查看consul服务时，我发现在容器构建中例如comment和auth这些docker似乎并没有构建。
  我想请问 1、在src/service中的代码是如何启动的呢（我的理解是这些是服务端）？ 2、是否comment和auth这些docker似乎并没有构建成功，因为在dockerfile中我没有找到启动服务的地址。

  抱歉打扰，期待您的回复。
  
  PS：不知道是否这个项目有交流群？
